language: perl
perl:
  - "5.8.8"       # common, prebuilt version
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - dev
matrix:
  allow_failures:
    - perl: blead
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libssl-dev # for IO::Socket::SSL
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install ExtUtils::MakeMaker~6.68
  - cpan-install --deps
script:
  - cd $BUILD_DIR
  - perl Makefile.PL && make
  - prove -blv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^blocked/
