---
abstract: 'Check your Postbank.de bank account from Perl'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  MIME::Lite: '3'
  Test::MockObject: '0'
  Test::More: '0'
  Text::Balanced: '0'
  Text::Table: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-Bank-Postbank_de
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '0'
  HTTP::CookieJar::LWP: '0'
  IO::Socket::SSL: '0'
  LWP::Protocol::https: '0'
  List::Sliding::Changes: '0.02'
  Moo: '2'
  Mozilla::CA: '0'
  WWW::Mechanize: '1.52'
  perl: '5.008'
resources:
  repository: git://github.com/Corion/Finance-Bank-Postbank_de.git
version: '0.52'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
