# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-Postbank_de
version:      0.23
version_from: lib/Finance/Bank/Postbank_de.pm
installdirs:  site
requires:
    Class::Accessor:               0
    List::Sliding::Changes:        0.02
    MIME::Lite:                    3
    Test::MockObject:              0
    Test::More:                    0
    WWW::Mechanize:                0.64

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
